# Generated by Django 4.0.4 on 2022-05-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_location_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_personal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
